"""Add wallet_logs table

Revision ID: 0700c6c27ae3
Revises: c3a6b7d1e8f9
Create Date: 2025-08-06 21:39:10.133278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0700c6c27ae3'
down_revision: Union[str, Sequence[str], None] = 'c3a6b7d1e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('balance', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_logs_id'), 'wallet_logs', ['id'], unique=False)
    op.drop_constraint(op.f('uix_user_currency_network'), 'wallets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_user_currency_network'), 'wallets', ['user_id', 'currency', 'network'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_wallet_logs_id'), table_name='wallet_logs')
    op.drop_table('wallet_logs')
    # ### end Alembic commands ###
